openapi: 3.1.0
info:
  title: Screeps API
  description: API for interacting with the Screeps game server, focusing on room and creeps interactions
  version: "1.0.0"
servers:
  - url: "https://screeps.com/api"
components:
  schemas:
    RoomStatus:
      type: object
      properties:
        room:
          type: string
        status:
          type: string
        owner:
          type: object
          properties:
            username:
              type: string
            level:
              type: integer
    TerrainData:
      type: object
      properties:
        terrain:
          type: array
          items:
            type: object
            properties:
              x:
                type: integer
              y:
                type: integer
              type:
                type: string
    CreepInfo:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
          name:
            type: string
          body:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                hits:
                  type: integer
          hits:
            type: integer
          hitsMax:
            type: integer
          energy:
            type: integer
          energyCapacity:
            type: integer
          spawning:
            type: boolean
paths:
  /game/room-overview:
    get:
      summary: Get an overview of a game room
      operationId: getRoomOverview
      parameters:
        - name: shard
          in: query
          required: true
          schema:
            type: string
          description: our hive is on shard3
        - name: interval
          in: query
          required: true
          schema:
            type: integer
          description: The interval in ticks for the overview data.
        - name: room
          in: query
          required: true
          schema:
            type: string
          description: The name of the room to get an overview for. We are Wooden Robot. Our rooms are E51N15 through E53N17
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: integer
                  data:
                    type: object
                    properties:
                      energyHarvested:
                        type: integer
                      energyControl:
                        type: integer
                      energySpentOnConstruction:
                        type: integer
                      energySpentOnCreeps:
                        type: integer
                      controllerProgress:
                        type: integer
                      controllerProgressTotal:
                        type: integer
                      controllerLevel:
                        type: integer
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Room not found

  /user/memory:
    get:
      summary: Get User Memory
      operationId: getUserMemory
      tags:
        - User
      parameters:
        - in: query
          name: shard
          schema:
            type: string
          required: false
          description: The name of the shard to retrieve memory from.
        - in: query
          name: path
          schema:
            type: string
          required: false
          description: The path within memory to retrieve.
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  user:
                    type: string
                  shard:
                    type: string
                  memory:
                    type: object
                    additionalProperties: true
  /user/code:
    get:
      summary: Get the current state of the code in your colony
      operationId: getUserCode
      security:
        - TokenAuth: []
      parameters:
        - in: query
          name: shard
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of user's creeps
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreepInfo"
  /user/console:
    post:
      summary: Execute a command in the Screeps console
      operationId: executeCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - expression
                - shard
              properties:
                expression:
                  type: string
                  description: The console command expression to be executed. If unspecified, console.log("Hello World");
                shard:
                  type: string
                  description: The shard where the command should be executed. We use 'shard3'.
                  example: "shard3"
      responses:
        "200":
          description: Command executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: integer
                    description: Indicates if the request was successful.
                  result:
                    type: object
                    properties:
                      ok:
                        type: integer
                        description: Indicates if the command execution was successful.
                      n:
                        type: integer
                        description: The number of operations executed.
                  ops:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: string
                          description: The user who executed the command.
                        expression:
                          type: string
                          description: The expression that was executed.
                        _id:
                          type: string
                          description: MongoDB ID of the operation.
                  insertedCount:
                    type: integer
                    description: The number of documents inserted into the database.
                  insertedIds:
                    type: array
                    items:
                      type: string
                      description: MongoDB IDs for the inserted documents.
  /game/room-terrain:
    get:
      summary: Get terrain data for a specific room
      operationId: getRoomTerrain
      parameters:
        - name: room
          in: query
          required: true
          schema:
            type: string
          description: The name of the room (e.g., E55S18)
        - name: shard
          in: query
          required: true
          schema:
            type: string
          description: The name of the shard (e.g., shard3)
      responses:
        '200':
          description: Terrain data for the room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TerrainData'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Room not found
  /game/room-objects:
    get:
      summary: Get objects in a room
      operationId: getRoomObjects
      parameters:
        - name: room
          in: query
          required: true
          schema:
            type: string
          description: The name of the room (e.g., E55S18)
        - name: shard
          in: query
          required: true
          schema:
            type: string
          description: The name of the shard (e.g., shard3)
      responses:
        '200':
          description: Objects in the room
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: integer
                  data:
                    type: object
                    properties:
                      room:
                        type: string
                      status:
                        type: string
                      owner:
                        $ref: '#/components/schemas/RoomStatus'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Room not found
